export * from './icon-cook-pot'
export * from './icon-location'
export * from './icon-minus'
export * from './icon-note'
export * from './icon-oa-verified'
export * from './icon-post-notif'
export * from './icon-restaurant'
export * from './icon-shopping-cart'
